# Generated by Django 5.2.8 on 2025-11-24 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LevelStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl_id', models.IntegerField()),
                ('attempts', models.IntegerField(default=0)),
                ('best_time', models.FloatField(blank=True, null=True)),
                ('coins', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='happyapp.player')),
            ],
            options={
                'indexes': [models.Index(fields=['lvl_id'], name='happyapp_le_lvl_id_0af432_idx'), models.Index(fields=['best_time'], name='happyapp_le_best_ti_3f6e9d_idx')],
                'unique_together': {('player', 'lvl_id')},
            },
        ),
    ]
